name: Setup
description: All the boring stuff.

runs:
  using: "composite"
  steps:
    - name: Cache tools
      id: cache-tools
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      env:
        cache-name: cache-tools
      with:
        path: tools
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Makefile') }}

    - name: Set up Java
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
      with:
        distribution: microsoft
        java-version: "17"

    - name: Set up Node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
      with:
        node-version: "18"

    - name: Install misc tools
      shell: bash
      run: |
        brew install coreutils gettext graphicsmagick imagemagick tree wine-stable
