name: Setup
description: All the boring stuff.

runs:
  using: "composite"
  steps:
    - name: Cache tools
      id: cache-tools
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      env:
        cache-name: cache-tools
      with:
        path: tools
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Makefile') }}

    - name: Set up Java
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
      with:
        distribution: microsoft
        java-version: "17"

    - name: Set up Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: "24"

    - name: Install misc tools
      shell: bash
      run: |
        brew install coreutils gettext graphicsmagick imagemagick tree wine-stable
