name: Setup
description: All the boring stuff.

runs:
  using: "composite"
  steps:
    - name: Cache tools
      id: cache-tools
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      env:
        cache-name: cache-tools
      with:
        path: tools
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Makefile') }}

    - name: Set up Java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      with:
        distribution: microsoft
        java-version: "17"

    - name: Set up Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: "18"

    - name: Install misc tools
      shell: bash
      run: |
        brew install coreutils gettext graphicsmagick imagemagick tree wine-stable
