name: Pull Request

on:
  pull_request:
    branches: main

jobs:
  pull_request:
    name: Pull Request
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        env:
          APP_VERSION: "0.0.1"
        run: |
          make resolve test-macos-x86
          make clean dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: artifacts
          path: |
            dist/**/*.dmg
            dist/**/*.zip
