name: Pull Request

on:
  pull_request:
    branches: main

jobs:
  pull_request:
    name: Pull Request
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        env:
          APP_VERSION: "0.0.1"
        run: |
          make resolve test-macos-x86
          make clean dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: artifacts
          path: |
            dist/**/*.dmg
            dist/**/*.zip
